services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildConfig:
      packages:
        - build-essential
        - cmake
        - libopenblas-dev
        - liblapack-dev
        - libx11-dev
        - libgtk-3-dev 