// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnebxrslcmdozitccwxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZWJ4cnNsY21kb3ppdGNjd3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NjA3NzYsImV4cCI6MjA3NzAzNjc3Nn0.ctslNjJffkNaevx8TqHQNUfsa4_cyq5TY21vRnvo-c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);